apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template: 
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: book-service:k8s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: config
          mountPath: /app/appsettings.Production.json
          subPath: appsettings.Production.json
      volumes:
      - name: config
        configMap:
          name: book-service-config
