global:
  scrape_interval: 15s 
scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'book-app-services'
    metrics_path: /metrics 
    static_configs:
      - targets: 
          - 'book-service:8080'
          - 'grpc-book-service:8080'
          - 'grpc-author-service:8080'
          - 'gateway-service:8080'

