global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'book-service'
    static_configs:
      - targets: ['book-service:8080']
        labels:
          service: 'book-service'

  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:8080']
        labels:
          service: 'gateway-service'

